#pragma once

#include <nlohmann/json.hpp>

enum class COORDINATOR_NAME { TIMEOUT_BASED, PHYS_TIMEOUT_BASED, DUMMY };

NLOHMANN_JSON_SERIALIZE_ENUM(
    COORDINATOR_NAME,
    {{COORDINATOR_NAME::TIMEOUT_BASED, "TIMEOUT_BASED"},
     {COORDINATOR_NAME::PHYS_TIMEOUT_BASED, "PHYS_TIMEOUT_BASED"},
     {COORDINATOR_NAME::DUMMY, "DUMMY"}})
